version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "5173:80" 
    restart: unless-stopped
